# Generated by Django 5.2.15 on 2026-07-06 18:47

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='books.category')),
            ],
            options={
                'verbose_name_plural': 'categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('subtitle', models.CharField(blank=True, max_length=500)),
                ('author_id', models.UUIDField(db_index=True)),
                ('author_name', models.CharField(max_length=200)),
                ('firm_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('tier', models.CharField(choices=[('firm', 'Firm Library'), ('general', 'General Library')], max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('under_review', 'Under Review'), ('published', 'Published'), ('rejected', 'Rejected'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('abstract', models.TextField(blank=True)),
                ('content', models.TextField()),
                ('year', models.PositiveIntegerField(blank=True, null=True)),
                ('edition', models.PositiveIntegerField(default=1)),
                ('language', models.CharField(default='en', max_length=10)),
                ('jurisdiction', models.CharField(default='Cameroon', max_length=100)),
                ('legal_areas', models.JSONField(default=list)),
                ('version_number', models.PositiveIntegerField(default=1)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_by_id', models.UUIDField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categories', models.ManyToManyField(blank=True, to='books.category')),
            ],
            options={
                'ordering': ['-published_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BookVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version_number', models.PositiveIntegerField()),
                ('content', models.TextField()),
                ('change_summary', models.TextField(blank=True)),
                ('created_by_id', models.UUIDField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='books.book')),
            ],
            options={
                'ordering': ['-version_number'],
                'unique_together': {('book', 'version_number')},
            },
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['tier', 'status'], name='books_book_tier_54616c_idx'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['author_id'], name='books_book_author__709385_idx'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['firm_id', 'status'], name='books_book_firm_id_a5e350_idx'),
        ),
    ]
