# Generated by Django 4.2.7 on 2026-07-23 20:23

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_book_views_featured'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookCompletion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('lawyer_id', models.UUIDField(db_index=True)),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CLECredit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('lawyer_id', models.UUIDField(db_index=True)),
                ('category', models.CharField(choices=[('reading', 'Library Reading'), ('authorship', 'Published Authorship'), ('article', 'Published Article'), ('contribution', 'Peer Contribution')], max_length=20)),
                ('credits', models.PositiveSmallIntegerField(default=1)),
                ('title', models.CharField(max_length=500)),
                ('reference_id', models.CharField(blank=True, default='', max_length=64)),
                ('earned_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-earned_at'],
            },
        ),
        migrations.RenameIndex(
            model_name='article',
            new_name='books_artic_status_6506c6_idx',
            old_name='books_article_status_tier_idx',
        ),
        migrations.RenameIndex(
            model_name='article',
            new_name='books_artic_author__a12821_idx',
            old_name='books_article_author_idx',
        ),
        migrations.RenameIndex(
            model_name='article',
            new_name='books_artic_article_c78e7f_idx',
            old_name='books_article_type_status_idx',
        ),
        migrations.AlterField(
            model_name='article',
            name='reading_time',
            field=models.PositiveSmallIntegerField(default=1, help_text='Minutes'),
        ),
        migrations.AddIndex(
            model_name='clecredit',
            index=models.Index(fields=['lawyer_id', 'earned_at'], name='books_clecr_lawyer__679a14_idx'),
        ),
        migrations.AddField(
            model_name='bookcompletion',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completions', to='books.book'),
        ),
        migrations.AlterUniqueTogether(
            name='bookcompletion',
            unique_together={('lawyer_id', 'book')},
        ),
    ]
