# Generated by Django 4.2.7 on 2026-07-23 20:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('lawyers', '0004_lawyerprofile_reputation_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='MentorshipRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mentee_id', models.UUIDField(db_index=True)),
                ('mentor_id', models.UUIDField(db_index=True)),
                ('message', models.TextField(blank=True, default='')),
                ('focus_area', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('ended', 'Ended')], db_index=True, default='pending', max_length=16)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.RenameIndex(
            model_name='lawyeravailability',
            new_name='lawyers_law_lawyer__65d4c0_idx',
            old_name='lawyers_av_lawyer_idx',
        ),
        migrations.RenameIndex(
            model_name='lawyerprofile',
            new_name='lawyers_law_special_196731_idx',
            old_name='lawyers_la_special_idx',
        ),
        migrations.RenameIndex(
            model_name='lawyerprofile',
            new_name='lawyers_law_bijural_4b92d3_idx',
            old_name='lawyers_la_bijural_idx',
        ),
        migrations.RenameIndex(
            model_name='lawyerprofile',
            new_name='lawyers_law_availab_f8a46b_idx',
            old_name='lawyers_la_avail_idx',
        ),
        migrations.RenameIndex(
            model_name='lawyerprofile',
            new_name='lawyers_law_average_0e7c75_idx',
            old_name='lawyers_la_rating_idx',
        ),
        migrations.AddField(
            model_name='lawyerprofile',
            name='mentorship_note',
            field=models.TextField(blank=True, default='', help_text='What you offer as a mentor, or what you seek as a mentee'),
        ),
        migrations.AddField(
            model_name='lawyerprofile',
            name='open_to_mentoring',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='lawyerprofile',
            name='seeking_mentor',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='lawyerprofile',
            name='procedural_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='lawyerprofile',
            name='professional_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterUniqueTogether(
            name='mentorshiprequest',
            unique_together={('mentee_id', 'mentor_id')},
        ),
    ]
