# Generated by Django 5.2.16 on 2026-07-13 07:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OutreachFirm',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('firm_name', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('country', models.CharField(default='Cameroon', max_length=100)),
                ('address', models.TextField(blank=True, default='')),
                ('website', models.CharField(blank=True, default='', max_length=255)),
                ('phone', models.CharField(blank=True, default='', max_length=50)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('practice_areas', models.JSONField(default=list)),
                ('firm_size', models.CharField(blank=True, default='', max_length=20)),
                ('status', models.CharField(choices=[('not_contacted', 'Not Contacted'), ('contacted', 'Contacted'), ('meeting_requested', 'Meeting Requested'), ('meeting_scheduled', 'Meeting Scheduled'), ('interview_completed', 'Interview Completed'), ('interested', 'Interested'), ('follow_up_needed', 'Follow-Up Needed'), ('joined_founding_network', 'Founding Network'), ('founding_council_member', 'Founding Council'), ('pilot_partner', 'Pilot Partner'), ('active_partner', 'Active Partner')], default='not_contacted', max_length=50)),
                ('source', models.CharField(blank=True, default='', max_length=50)),
                ('tags', models.JSONField(default=list)),
                ('assigned_to', models.CharField(blank=True, default='', max_length=100)),
                ('last_contact', models.DateField(blank=True, null=True)),
                ('next_followup', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('firm_name', models.CharField(max_length=255)),
                ('contact_name', models.CharField(blank=True, default='', max_length=255)),
                ('date', models.DateField()),
                ('time', models.CharField(blank=True, default='', max_length=10)),
                ('duration', models.PositiveIntegerField(blank=True, null=True)),
                ('type', models.CharField(choices=[('in_person', 'In Person'), ('virtual', 'Virtual'), ('phone', 'Phone')], default='virtual', max_length=20)),
                ('location', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('rescheduled', 'Rescheduled')], default='scheduled', max_length=20)),
                ('interviewer_name', models.CharField(blank=True, default='', max_length=100)),
                ('summary', models.TextField(blank=True, default='')),
                ('takeaways', models.JSONField(default=list)),
                ('next_steps', models.JSONField(default=list)),
                ('overall_interest_level', models.PositiveIntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('firm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviews', to='outreach.outreachfirm')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FeatureRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('requested_by', models.CharField(blank=True, default='', max_length=255)),
                ('firm_name', models.CharField(blank=True, default='', max_length=255)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10)),
                ('status', models.CharField(choices=[('under_review', 'Under Review'), ('approved', 'Approved'), ('planned', 'Planned'), ('in_development', 'In Development'), ('released', 'Released'), ('declined', 'Declined')], default='under_review', max_length=20)),
                ('source', models.CharField(choices=[('interview', 'Interview'), ('firm', 'Firm'), ('internal', 'Internal'), ('email', 'Email')], default='interview', max_length=20)),
                ('description', models.TextField(blank=True, default='')),
                ('requested_on', models.DateField()),
                ('interview_id', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('firm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feature_requests', to='outreach.outreachfirm')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('firm_name', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('position', models.CharField(blank=True, default='', max_length=255)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('phone', models.CharField(blank=True, default='', max_length=50)),
                ('whatsapp', models.CharField(blank=True, default='', max_length=50)),
                ('linkedin', models.CharField(blank=True, default='', max_length=255)),
                ('is_primary', models.BooleanField(default=False)),
                ('firm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='outreach.outreachfirm')),
            ],
            options={
                'ordering': ['-is_primary', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('assigned_to', models.CharField(blank=True, default='', max_length=100)),
                ('firm_name', models.CharField(blank=True, default='', max_length=255)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('done', 'Done')], default='pending', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('firm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='outreach.outreachfirm')),
            ],
            options={
                'ordering': ['due_date', '-created_at'],
            },
        ),
    ]
