from django.urls import path
from .verification_views import (
    FirmVerificationSubmitView,
    FirmVerificationQueueView,
    FirmVerificationActionView,
)
from .views import (
    FirmBrowseView,
    FirmSearchView,
    FirmDetailView,
    FirmMembersView,
    FirmLawyersView,
    MyFirmMembershipsView,
    FirmCreateView,
    InviteCreateView,
    InviteCancelView,
    FirmPendingInvitesView,
    FirmActionLogView,
    FirmLogoUploadView,
    FirmLogoServeView,
    InviteAcceptView,
    MemberRoleUpdateView,
    MemberAssignFirmView,
    MemberDeleteView,
    UserFirmMembershipsView,
    FirmPartnershipPolicyView,
    PartnershipRequestCreateView,
    PartnershipRequestListView,
    PartnershipRequestRespondView,
)

urlpatterns = [
    path('', FirmBrowseView.as_view(), name='firm-browse'),
    path('create/', FirmCreateView.as_view(), name='firm-create'),
    path('search/', FirmSearchView.as_view(), name='firm-search'),
    path('<int:firm_id>/', FirmDetailView.as_view(), name='firm-detail'),
    path('me/', MyFirmMembershipsView.as_view(), name='my-firm-memberships'),
    path('<int:firm_id>/members/', FirmMembersView.as_view(), name='firm-members'),
    path('<int:firm_id>/lawyers/', FirmLawyersView.as_view(), name='firm-lawyers'),
    path('<int:firm_id>/invites/', InviteCreateView.as_view(), name='firm-invites'),
    path('<int:firm_id>/invites/<uuid:token>/', InviteCancelView.as_view(), name='firm-invite-cancel'),
    path('<int:firm_id>/pending-invites/', FirmPendingInvitesView.as_view(), name='firm-pending-invites'),
    path('<int:firm_id>/activity/', FirmActionLogView.as_view(), name='firm-activity'),
    path('<int:firm_id>/logo/', FirmLogoUploadView.as_view(), name='firm-logo-upload'),
    path('logo/<int:firm_id>/', FirmLogoServeView.as_view(), name='firm-logo-serve'),
    path('invites/<uuid:token>/accept/', InviteAcceptView.as_view(), name='invite-accept'),
    path('internal/users/<uuid:user_id>/memberships/', UserFirmMembershipsView.as_view(), name='user-firm-memberships'),
    path('members/<int:member_id>/role/', MemberRoleUpdateView.as_view(), name='member-role-update'),
    path('members/<int:member_id>/firm/', MemberAssignFirmView.as_view(), name='member-assign-firm'),
    path('members/<int:member_id>/', MemberDeleteView.as_view(), name='member-delete'),
    # Partnership
    path('<int:firm_id>/partnership-policy/', FirmPartnershipPolicyView.as_view(), name='firm-partnership-policy'),
    path('<int:firm_id>/partnership-request/', PartnershipRequestCreateView.as_view(), name='firm-partnership-request-create'),
    path('<int:firm_id>/partnership-requests/', PartnershipRequestListView.as_view(), name='firm-partnership-requests'),
    path('partnership-requests/<int:pk>/', PartnershipRequestRespondView.as_view(), name='partnership-request-respond'),
    # Firm verification
    path('verification/', FirmVerificationSubmitView.as_view(), name='firm-verification-submit'),
    path('verification/queue/', FirmVerificationQueueView.as_view(), name='firm-verification-queue'),
    path('verification/<uuid:pk>/<str:action>/', FirmVerificationActionView.as_view(), name='firm-verification-action'),
]
