# Generated by Django 5.2.15 on 2026-07-03 06:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Thread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thread_type', models.CharField(choices=[('client_lawyer', 'Client ↔ Lawyer'), ('client_firm', 'Client ↔ Firm'), ('client_support', 'Client ↔ Support'), ('firm_internal', 'Firm Internal')], db_index=True, max_length=20)),
                ('case_id', models.IntegerField(db_index=True)),
                ('case_ref', models.CharField(blank=True, max_length=50)),
                ('case_title', models.CharField(blank=True, max_length=200)),
                ('subject', models.CharField(blank=True, max_length=200)),
                ('is_ai_support', models.BooleanField(default=False)),
                ('escalated_to_human', models.BooleanField(default=False)),
                ('is_closed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_id', models.CharField(db_index=True, max_length=36)),
                ('sender_name', models.CharField(max_length=100)),
                ('sender_role', models.CharField(max_length=20)),
                ('content', models.TextField()),
                ('is_ai', models.BooleanField(default=False)),
                ('is_system', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('edited_at', models.DateTimeField(blank=True, null=True)),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='messaging.thread')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='MessageReaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=36)),
                ('display_name', models.CharField(max_length=100)),
                ('emoji', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='messaging.message')),
            ],
            options={
                'unique_together': {('message', 'user_id', 'emoji')},
            },
        ),
        migrations.CreateModel(
            name='ThreadParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(db_index=True, max_length=36)),
                ('display_name', models.CharField(max_length=100)),
                ('role', models.CharField(choices=[('client', 'Client'), ('lawyer', 'Lawyer'), ('firm_admin', 'Firm Admin'), ('support', 'Support')], max_length=20)),
                ('firm_id', models.IntegerField(blank=True, null=True)),
                ('last_read_at', models.DateTimeField(blank=True, null=True)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='messaging.thread')),
            ],
            options={
                'unique_together': {('thread', 'user_id')},
            },
        ),
    ]
