# Generated by Django 4.2.7 on 2026-07-23 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='referral',
            name='fee_split_pct',
            field=models.PositiveSmallIntegerField(default=0, help_text="Referrer's agreed share of the professional fee, 0-100%"),
        ),
        migrations.AddField(
            model_name='referral',
            name='outcome_note',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='referral',
            name='responded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='feeditem',
            name='item_type',
            field=models.CharField(choices=[('article', 'Article'), ('referral_accepted', 'Referral Accepted'), ('referral_completed', 'Referral Completed'), ('follow', 'New Follow'), ('partnership', 'Partnership'), ('case_won', 'Case Won / Verdict'), ('case_settled', 'Case Settled'), ('lawyer_verified', 'Lawyer Verified'), ('tier_reached', 'Reputation Tier Reached'), ('capacity_open', 'Open to New Matters')], db_index=True, max_length=30),
        ),
    ]
