# Generated by Django 4.2.7 on 2026-07-22 19:17

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0006_case_booking_status_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adjournment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hearing_date', models.DateField(help_text='The hearing date that was adjourned')),
                ('reason', models.CharField(choices=[('judge_absent', 'Judge Absent'), ('opposing_counsel_absent', 'Opposing Counsel Absent'), ('counsel_request', 'Counsel Requested Adjournment'), ('ruling_not_ready', 'Ruling / Judgment Not Ready'), ('party_absent', 'Party Absent / Not Served'), ('court_congestion', 'Court Congestion / List Not Reached'), ('evidence_pending', 'Evidence / Expert Report Pending'), ('settlement_talks', 'Settlement Negotiations Ongoing'), ('strike_action', 'Court Staff / Bar Strike'), ('other', 'Other')], default='other', max_length=32)),
                ('reason_detail', models.TextField(blank=True, default='')),
                ('adjourned_to', models.DateField(blank=True, help_text='New hearing date, if fixed', null=True)),
                ('recorded_by', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-hearing_date'],
            },
        ),
        migrations.CreateModel(
            name='CaseDeadline',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deadline_type', models.CharField(choices=[('appeal_window', 'Appeal Window'), ('prescription', 'Prescription / Limitation Period'), ('conclusions_due', 'Conclusions / Submissions Due'), ('service_deadline', 'Service of Process Deadline'), ('opposition_window', 'Opposition Window (OHADA)'), ('payment_deadline', 'Payment Deadline'), ('detention_review', 'Detention Review'), ('procedural_step', 'Procedural Step'), ('custom', 'Custom')], default='custom', max_length=32)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('due_date', models.DateField(db_index=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('met', 'Met'), ('missed', 'Missed'), ('waived', 'Waived / No Longer Applicable')], default='pending', max_length=16)),
                ('source', models.CharField(blank=True, default='manual', help_text='manual | procedure_template | hearing_outcome | detention', max_length=32)),
                ('alert_7d_sent', models.BooleanField(default=False)),
                ('alert_1d_sent', models.BooleanField(default=False)),
                ('overdue_alert_sent', models.BooleanField(default=False)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['due_date'],
            },
        ),
        migrations.CreateModel(
            name='CaseParty',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('plaintiff', 'Plaintiff / Demandeur'), ('co_plaintiff', 'Co-Plaintiff'), ('defendant', 'Defendant / Defendeur'), ('co_defendant', 'Co-Defendant'), ('opposing_counsel', 'Opposing Counsel'), ('witness', 'Witness'), ('expert', 'Expert'), ('interested_party', 'Interested Party'), ('bailiff', 'Bailiff / Huissier')], max_length=32)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('organization', models.CharField(blank=True, default='', max_length=255)),
                ('phone', models.CharField(blank=True, default='', max_length=32)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('notes', models.TextField(blank=True, default='')),
                ('added_by', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['role', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CaseProcedureStep',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('template_key', models.CharField(db_index=True, max_length=64)),
                ('step_order', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('due_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('done', 'Done'), ('skipped', 'Skipped')], default='pending', max_length=16)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['step_order'],
            },
        ),
        migrations.CreateModel(
            name='ConciliationRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('forum', models.CharField(choices=[('labour_inspector', 'Labour Inspector'), ('family_conciliation', 'Family / Divorce Conciliation'), ('customary_authority', 'Customary Authority'), ('private_mediation', 'Private Mediation'), ('other', 'Other')], max_length=32)),
                ('required', models.BooleanField(default=True, help_text='Whether conciliation is a statutory precondition to filing')),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('successful', 'Successful — Dispute Resolved'), ('failed', 'Failed — PV of Non-Conciliation Issued')], default='not_started', max_length=16)),
                ('scheduled_date', models.DateField(blank=True, null=True)),
                ('completed_date', models.DateField(blank=True, null=True)),
                ('outcome_summary', models.TextField(blank=True, default='')),
                ('pv_reference', models.CharField(blank=True, default='', help_text='Proces-verbal de non-conciliation reference — required to file at court', max_length=128)),
                ('recorded_by', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DetentionRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('detention_type', models.CharField(choices=[('garde_a_vue', 'Garde a Vue (Police Custody)'), ('detention_provisoire', 'Detention Provisoire (Remand)')], max_length=32)),
                ('person_name', models.CharField(max_length=255)),
                ('facility', models.CharField(blank=True, default='', max_length=255)),
                ('start_date', models.DateField()),
                ('statutory_limit_days', models.PositiveIntegerField(help_text='Statutory limit in days (e.g. 2 for garde a vue, 180/365 for remand)')),
                ('extensions_days', models.PositiveIntegerField(default=0, help_text='Total additional days granted by renewal orders')),
                ('released', models.BooleanField(default=False)),
                ('released_on', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('alert_sent', models.BooleanField(default=False)),
                ('recorded_by', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Disbursement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('court_fees', 'Court / Filing Fees'), ('stamp_duty', 'Stamp Duty (Timbres)'), ('bailiff_fees', 'Bailiff / Huissier Fees'), ('expert_fees', 'Expert Fees'), ('registration_fees', 'Registration Fees'), ('copies_certification', 'Copies & Certification'), ('travel', 'Travel & Transport'), ('other', 'Other')], default='other', max_length=32)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('amount', models.DecimalField(decimal_places=0, help_text='Amount in XAF', max_digits=12)),
                ('incurred_on', models.DateField()),
                ('billable', models.BooleanField(default=True)),
                ('reimbursed', models.BooleanField(default=False)),
                ('receipt_reference', models.CharField(blank=True, default='', max_length=128)),
                ('recorded_by', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-incurred_on'],
            },
        ),
        migrations.CreateModel(
            name='HearingOutcome',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hearing_date', models.DateField()),
                ('outcome', models.CharField(choices=[('held_proceeded', 'Hearing Held — Matter Proceeded'), ('adjourned', 'Adjourned'), ('ruling_delivered', 'Ruling Delivered'), ('judgment_delivered', 'Judgment Delivered'), ('struck_out', 'Struck Out'), ('settled', 'Settled'), ('other', 'Other')], max_length=32)),
                ('summary', models.TextField(blank=True, default='')),
                ('next_hearing_date', models.DateField(blank=True, null=True)),
                ('next_action', models.CharField(blank=True, default='', help_text='What must happen before the next hearing', max_length=255)),
                ('adjournment_reason', models.CharField(blank=True, default='', help_text='If outcome=adjourned: reason code mirrored into the Adjournment log', max_length=32)),
                ('recorded_by', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-hearing_date'],
            },
        ),
        migrations.RenameIndex(
            model_name='case',
            new_name='cases_case_client__c6764b_idx',
            old_name='cases_case_client__idx',
        ),
        migrations.RenameIndex(
            model_name='case',
            new_name='cases_case_status_5f99d2_idx',
            old_name='cases_case_status_idx',
        ),
        migrations.RenameIndex(
            model_name='case',
            new_name='cases_case_assigne_e47633_idx',
            old_name='cases_case_lawyer_idx',
        ),
        migrations.RenameIndex(
            model_name='case',
            new_name='cases_case_created_a9dee7_idx',
            old_name='cases_case_created_idx',
        ),
        migrations.AddField(
            model_name='case',
            name='chamber',
            field=models.CharField(blank=True, default='', help_text='Chamber/section handling the matter, e.g. "Chambre civile"', max_length=128),
        ),
        migrations.AddField(
            model_name='case',
            name='court_level',
            field=models.CharField(blank=True, choices=[('customary_court', 'Customary Court'), ('first_instance', 'Court of First Instance (TPI)'), ('high_court', 'High Court (TGI)'), ('appeal_court', 'Court of Appeal'), ('supreme_court', 'Supreme Court'), ('administrative_court', 'Administrative Court'), ('military_tribunal', 'Military Tribunal'), ('labour_bench', 'Labour Bench'), ('other', 'Other')], default='', max_length=32),
        ),
        migrations.AddField(
            model_name='case',
            name='court_location',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='case',
            name='court_name',
            field=models.CharField(blank=True, default='', help_text='e.g. "TPI Douala-Bonanjo", "Court of Appeal of the Northwest"', max_length=255),
        ),
        migrations.AddField(
            model_name='case',
            name='judge_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='case',
            name='parent_case',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_cases', to='cases.case'),
        ),
        migrations.AddField(
            model_name='case',
            name='relation_type',
            field=models.CharField(blank=True, choices=[('appeal_of', 'Appeal of'), ('related_to', 'Related to'), ('consolidated_with', 'Consolidated with')], default='', max_length=32),
        ),
        migrations.AddField(
            model_name='case',
            name='suit_number',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Registry suit number / numéro de rôle assigned by the court registry', max_length=128),
        ),
        migrations.AlterField(
            model_name='case',
            name='booking_metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Stores consultation_type, booking_fee, payment_reference, payment_status, target info'),
        ),
        migrations.AlterField(
            model_name='case',
            name='legal_tradition',
            field=models.CharField(choices=[('common_law', 'Common Law'), ('civil_law', 'Civil Law'), ('customary', 'Customary Law')], max_length=32),
        ),
        migrations.AlterField(
            model_name='case',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('filed', 'Filed'), ('assigned', 'Assigned to Lawyer'), ('under_review', 'Under Review'), ('evidence_collection', 'Evidence Collection'), ('awaiting_court_date', 'Awaiting Court Date'), ('in_progress', 'In Progress'), ('hearing_scheduled', 'Hearing Scheduled'), ('hearing_adjourned', 'Hearing Adjourned'), ('mediation', 'Mediation'), ('verdict', 'Verdict Rendered'), ('settled', 'Settled Out of Court'), ('appeal_filed', 'Appeal Filed'), ('appeal_in_progress', 'Appeal in Progress'), ('closed', 'Closed'), ('dismissed', 'Dismissed'), ('archived', 'Archived')], default='draft', max_length=32),
        ),
        migrations.AlterField(
            model_name='case',
            name='timeline',
            field=models.JSONField(default=list, help_text='Array of {timestamp, status, notes}'),
        ),
        migrations.AlterField(
            model_name='caseapplication',
            name='firm_id',
            field=models.UUIDField(blank=True, help_text='Optional: firm the lawyer belongs to', null=True),
        ),
        migrations.AlterField(
            model_name='caseapplication',
            name='lawyer_id',
            field=models.UUIDField(help_text='UUID of the lawyer applying'),
        ),
        migrations.AlterField(
            model_name='reassignmentrequest',
            name='performance_rating',
            field=models.PositiveSmallIntegerField(default=3, help_text='1–5 star rating'),
        ),
        migrations.AddField(
            model_name='hearingoutcome',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hearing_outcomes', to='cases.case'),
        ),
        migrations.AddField(
            model_name='disbursement',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disbursements', to='cases.case'),
        ),
        migrations.AddField(
            model_name='detentionrecord',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detention_records', to='cases.case'),
        ),
        migrations.AddField(
            model_name='conciliationrecord',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conciliation_records', to='cases.case'),
        ),
        migrations.AddField(
            model_name='caseprocedurestep',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procedure_steps', to='cases.case'),
        ),
        migrations.AddField(
            model_name='caseparty',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parties', to='cases.case'),
        ),
        migrations.AddField(
            model_name='casedeadline',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deadlines', to='cases.case'),
        ),
        migrations.AddField(
            model_name='adjournment',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjournments', to='cases.case'),
        ),
        migrations.AlterUniqueTogether(
            name='caseprocedurestep',
            unique_together={('case', 'template_key', 'step_order')},
        ),
        migrations.AddIndex(
            model_name='caseparty',
            index=models.Index(fields=['case', 'role'], name='cases_casep_case_id_594109_idx'),
        ),
        migrations.AddIndex(
            model_name='casedeadline',
            index=models.Index(fields=['status', 'due_date'], name='cases_cased_status_1c35e8_idx'),
        ),
        migrations.AddIndex(
            model_name='adjournment',
            index=models.Index(fields=['case', 'hearing_date'], name='cases_adjou_case_id_e284b9_idx'),
        ),
    ]
