# Generated by Django 4.2.7 on 2026-07-23 20:15

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0007_adjournment_casedeadline_caseparty_caseprocedurestep_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseAuthority',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_type', models.CharField(choices=[('library_book', 'CamLex Book'), ('library_article', 'CamLex Article'), ('statute', 'Statute / Code'), ('ohada_act', 'OHADA Uniform Act'), ('judgment', 'Judgment / Case Law'), ('external', 'External Source')], default='statute', max_length=32)),
                ('title', models.CharField(max_length=500)),
                ('reference', models.CharField(blank=True, default='', help_text='Pinpoint citation, e.g. "AUDSC Art. 200-204" or "Labour Code s.39"', max_length=255)),
                ('library_id', models.CharField(blank=True, default='', help_text='CamLex book/article id when cited from the library', max_length=64)),
                ('url', models.URLField(blank=True, default='')),
                ('note', models.TextField(blank=True, default='', help_text='Why this authority is relevant here')),
                ('added_by', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authorities', to='cases.case')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
