from django.urls import path
from .views import (
    CaseListView, CaseDetailView, CaseAssignView, CaseNoteView,
    CaseStatusUpdateView, BookingAcceptView, BookingDeclineView, IncomingBookingsView,
    OpenCasesView, CaseApplicationView,
    ReassignmentView, ReassignmentConfirmView, ReassignmentCancelView,
    ReassignmentSelectLawyerView, ReassignmentRespondView,
    PaymentVerifyView,
    IntakeFormCreateView, IntakeFormPublicView, IntakeFormDetailView,
)
from .casefile_views import (
    AdjournmentListView, AdjournmentDetailView,
    CasePartyListView, CasePartyDetailView,
    CaseDeadlineListView, CaseDeadlineDetailView,
    DisbursementListView, DisbursementDetailView,
    HearingOutcomeListView, HearingOutcomeDetailView,
    DetentionRecordListView, DetentionRecordDetailView,
    ConciliationListView, ConciliationDetailView,
    ProcedureTemplateListView, ApplyProcedureTemplateView,
    ProcedureStepListView, ProcedureStepDetailView,
    ConflictCheckView, CourtInfoView,
)

urlpatterns = [
    path('', CaseListView.as_view(), name='case-list'),
    path('open/', OpenCasesView.as_view(), name='open-cases'),
    path('incoming-bookings/', IncomingBookingsView.as_view(), name='incoming-bookings'),
    path('<uuid:case_id>/', CaseDetailView.as_view(), name='case-detail'),
    path('<uuid:case_id>/assign/', CaseAssignView.as_view(), name='case-assign'),
    path('<uuid:case_id>/status/', CaseStatusUpdateView.as_view(), name='case-status-update'),
    path('<uuid:case_id>/notes/', CaseNoteView.as_view(), name='case-notes'),
    path('<uuid:case_id>/accept/', BookingAcceptView.as_view(), name='booking-accept'),
    path('<uuid:case_id>/decline/', BookingDeclineView.as_view(), name='booking-decline'),
    path('<uuid:case_id>/apply/', CaseApplicationView.as_view(), name='case-apply'),
    path('<uuid:case_id>/payment/verify/', PaymentVerifyView.as_view(), name='payment-verify'),
    path('<uuid:case_id>/reassignment/', ReassignmentView.as_view(), name='case-reassignment'),
    path('<uuid:case_id>/reassignment/confirm/', ReassignmentConfirmView.as_view(), name='case-reassignment-confirm'),
    path('<uuid:case_id>/reassignment/cancel/', ReassignmentCancelView.as_view(), name='case-reassignment-cancel'),
    path('<uuid:case_id>/reassignment/respond/', ReassignmentRespondView.as_view(), name='case-reassignment-respond'),
    path('<uuid:case_id>/reassignment/select-lawyer/', ReassignmentSelectLawyerView.as_view(), name='case-reassignment-select-lawyer'),
    path('intake/', IntakeFormCreateView.as_view(), name='intake-create'),
    path('intake/<uuid:token>/', IntakeFormPublicView.as_view(), name='intake-public'),
    path('intake/<uuid:token>/detail/', IntakeFormDetailView.as_view(), name='intake-detail'),

    # ── Case File 2.0 ────────────────────────────────────────────────────────
    path('procedure-templates/', ProcedureTemplateListView.as_view(), name='procedure-templates'),
    path('conflict-check/', ConflictCheckView.as_view(), name='conflict-check'),
    path('<uuid:case_id>/court/', CourtInfoView.as_view(), name='case-court-info'),
    path('<uuid:case_id>/adjournments/', AdjournmentListView.as_view(), name='case-adjournments'),
    path('<uuid:case_id>/adjournments/<uuid:item_id>/', AdjournmentDetailView.as_view(), name='case-adjournment-detail'),
    path('<uuid:case_id>/parties/', CasePartyListView.as_view(), name='case-parties'),
    path('<uuid:case_id>/parties/<uuid:item_id>/', CasePartyDetailView.as_view(), name='case-party-detail'),
    path('<uuid:case_id>/deadlines/', CaseDeadlineListView.as_view(), name='case-deadlines'),
    path('<uuid:case_id>/deadlines/<uuid:item_id>/', CaseDeadlineDetailView.as_view(), name='case-deadline-detail'),
    path('<uuid:case_id>/disbursements/', DisbursementListView.as_view(), name='case-disbursements'),
    path('<uuid:case_id>/disbursements/<uuid:item_id>/', DisbursementDetailView.as_view(), name='case-disbursement-detail'),
    path('<uuid:case_id>/hearing-outcomes/', HearingOutcomeListView.as_view(), name='case-hearing-outcomes'),
    path('<uuid:case_id>/hearing-outcomes/<uuid:item_id>/', HearingOutcomeDetailView.as_view(), name='case-hearing-outcome-detail'),
    path('<uuid:case_id>/detention/', DetentionRecordListView.as_view(), name='case-detention'),
    path('<uuid:case_id>/detention/<uuid:item_id>/', DetentionRecordDetailView.as_view(), name='case-detention-detail'),
    path('<uuid:case_id>/conciliation/', ConciliationListView.as_view(), name='case-conciliation'),
    path('<uuid:case_id>/conciliation/<uuid:item_id>/', ConciliationDetailView.as_view(), name='case-conciliation-detail'),
    path('<uuid:case_id>/apply-procedure/', ApplyProcedureTemplateView.as_view(), name='case-apply-procedure'),
    path('<uuid:case_id>/procedure-steps/', ProcedureStepListView.as_view(), name='case-procedure-steps'),
    path('<uuid:case_id>/procedure-steps/<uuid:item_id>/', ProcedureStepDetailView.as_view(), name='case-procedure-step-detail'),
]
