FROM python:3.11-slim
ENV PYTHONUNBUFFERED=1
WORKDIR /app

RUN apt-get update && apt-get install -y build-essential libpq-dev && rm -rf /var/lib/apt/lists/*

COPY requirements.txt /app/requirements.txt
RUN pip install --no-cache-dir -r /app/requirements.txt

COPY . /app
RUN chmod +x /app/wait-for-db.sh

EXPOSE 8005
CMD /app/wait-for-db.sh && python manage.py migrate --noinput && gunicorn core.wsgi:application --bind 0.0.0.0:8005
